services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
